### ISSUE TITLE
search results are ranked strangely

### ISSUE THREAD

**Issue by fev4** [stefanicjuraj/smart-search#1]
hey there, found the project interesting and wanted to report something (perhaps it's known already)

for example if I search for `getSlots` I get results such as this:
![Image](https://github.com/user-attachments/assets/2c4ce9ef-0b9f-4bdc-b6a7-d78122cdd23c)

where the first results point to:
```
#container * {
  box-sizing: border-box;
}
```

the actual results I want are all the way to the bottom:

![Image](https://github.com/user-attachments/assets/00845c5f-f2e8-45f4-89bf-bbdcd7fa242d)

I don't understand why the first result pops up for this query, which is rather unexpected

**Comment by fev4** [comment]
interestingly, if I search any gibberish, the same results appear, is the `*` from the results playing a role here? can't think of anything else

![Image](https://github.com/user-attachments/assets/402b6aa0-574b-4891-aff6-14bca028cc59)

these are the types of results it provides:


```css
#container * {
  box-sizing: border-box;
}
```

```css
  #container > * {
    width: 100%;
  }
```

```css
#description quiz-footer-content * {
  display: none;
}
```

the patterns I can see between these are:
- they are all matched as class and as a Symbol
- all their lines end with `* {`
